server:
  port: 8020
spring:
  application:
    name: app-itcast-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
#ribbon超时设置
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#开启Hystrix断路器
feign:
  hystrix:
    enabled: true
#Hystrix禁止服务超时时间,正常的情况下不允许设置false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false